### ISSUE TITLE
Any chance of Apple Music integration?

### ISSUE THREAD

**Issue by JustATechie** [AngryKiller/iTunes-Discord#15]
I realize this is intended for iTunes, but iTunes has been removed and replaced by the Music app in newer macOS versions.

**Comment by AngryKiller** [comment]
Did you test it using the Music app? It should be supported.

**Comment by JustATechie** [comment]
I did, it didnt recognize the music playing. I can do further testing to see why.

**Comment by AngryKiller** [comment]
Can you try running the example.js file of https://github.com/AngryKiller/iTunes-bridge in the terminal (after doing npm install of course) and playing/skipping/pausing tracks in the Music app to see what happens?

**Comment by AngryKiller** [comment]
Okay, I actually just tested it on Big Sur and it does not work so I'm investigating the issue

**Comment by AngryKiller** [comment]
I just pushed a fix on iTunes-bridge that should resolve issues with Catalina and later, just pull the repo and run `npm install`, it should work right now, tell me if it does for you

**Comment by AngryKiller** [comment]
Okayyy so now everything should work with both Mojave and lower, and Catalina and higher, just waiting for your approval to close the issue but there shouldn't be any issues anymore

**Comment by justatechie** [comment]
Ok it now recognizes that music is playing and the menu bar view shows the song title. The terminal also reflects this information. It does appear to be sending the information based on `Sent player informations to rpc!`. However discord is not projecting this information.

**Comment by justatechie** [comment]
I restarted discord and Apple music and it now seems to work perfectly! Thank you :)
