### ISSUE TITLE
ITUNES

### ISSUE THREAD

**Issue by PANOSPAP1982** [AngryKiller/iTunes-Discord#7]
hello my friend!!!tell me please this is for searching music...songs and albums from itunes?and if yes,please could you make a web version?I am begging you!!!

**Comment by AngryKiller** [comment]
Hi, this is an app to show the song you are listening to on your Discord profile. I however made a little module that can give you the iTunes link of a track from the track name and the artist, if that can help you: https://github.com/AngryKiller/get-apple-music-link (never tested it in a browser environment)

**Comment by PANOSPAP1982** [comment]
aaaa then my friend is not for searching songs and albums???
